slipstream/SlipStreamConnectors

stratuslab/python/tar/slipstream_stratuslab/StratusLabClientCloud.py, stratuslab/python/tar/slipstream_stratuslab/StratusLabIterClientCloud.py
for StratusLabIter connector.
Fixes #18
=> Updated implementation of VMs termination and volatile disks deletion

cloudstack/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackAdvancedZoneConnector.java, cloudstack/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackConnector.java, cloudstack/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackSystemConfigurationParametersFactory.java, openstack/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackSystemConfigurationParametersFactory.java
Connected to slipstream/SlipStream#77
Require:
- slipstream/SlipStreamServer#383
=> Choose cloud contextualization

cloudstack/rpm/pom.xml, occi/java/rpm/pom.xml, occi/python/rpm/pom.xml, openstack/rpm/pom.xml, physicalhost/rpm/pom.xml, stratuslab/java/rpm/pom.xml, stratuslab/python/rpm/pom.xml
Connected to slipstream/SlipStream#72.
=> fix python packaging for CentOS 7

cloudstack/rpm/pom.xml, occi/java/rpm/pom.xml, openstack/rpm/pom.xml, physicalhost/rpm/pom.xml, stratuslab/java/rpm/pom.xml
Connected to slipstream/SlipStreamServer#365.
=> reduce dependency from jdk to jre

physicalhost/jar/src/main/java/com/sixsq/slipstream/connector/physicalhost/PhysicalHostConnector.java, stratuslab/java/jar/src/test/java/com/sixsq/slipstream/connector/stratuslab/StratusLabConnectorTest2.java, stratuslab/python/tar/slipstream_stratuslab/StratusLabClientCloud.py
Connected to SixSq/tasklist#216
Require : 
- slipstream/SlipStreamServer#414
- slipstream/SlipStreamClient#149
Related to : 
- slipstream/SlipStreamUI#371
=> Extract new vm metrics

physicalhost/jar/src/main/java/com/sixsq/slipstream/connector/physicalhost/PhysicalHostConnector.java
Update physical connector for removal of SLIPSTREAM_REPORT_DIR java variable.
Connected to slipstream/SlipStreamClient#106.
=>  remove direct references to variable SLIPSTREAM_REPORT_DIR

opennebula/java/jar/pom.xml, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/InstanceType.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaImageParametersFactory.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaSystemConfigurationParametersFactory.java, opennebula/java/pom.xml, opennebula/java/rpm/pom.xml, opennebula/pom.xml, opennebula/python/pom.xml, opennebula/python/rpm/pom.xml, opennebula/python/tar/bin/opennebula-describe-instances, opennebula/python/tar/bin/opennebula-run-instances, opennebula/python/tar/pom.xml, opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py, opennebula/python/tar/slipstream_opennebula/OpenNebulaCommand.py
=> Opennebula connector 2.21

opennebula/python/tar/bin/opennebula-describe-instances, opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
=> build image working and usable

occi/java/jar/src/test/clojure/slipstream/credcache/common_test.clj
Intermediate pull request to be merged.  Must be merged with corresponding PRs in other repositories.
Connected to SixSq/tasklist#562.
=> dependency updates

occi/python/tar/slipstream_occi/OcciClientCloud.py, occi/python/tar/test/TestOcciClientCloud.py
=> fix: updated logic of extraction of proxy file name from UserInfo.

openstack/python/tar/bin/openstack-describe-instances
Tested on nuv.la - works.
Connected to #79
=> openstack new state 7 - Error

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py
Connected to slipstream/SlipStreamServer#547
=> OpenStack: Improved error messages.

stratuslab/python/tar/slipstream_stratuslab/StratusLabClientCloud.py
=> StratusLab: Improved logging in the case of a socket error.

cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py, cloudstack/python/tar/slipstream_cloudstack/LibcloudCloudstackPatch.py
=> CloudStack: Added support for multiple Zones.

openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackSystemConfigurationParametersFactory.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackUserParametersFactory.java, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackCommand.py
=> OpenStack: Added support for Identity API v3

openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackSystemConfigurationParametersFactory.java, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackCommand.py, openstack/python/tar/slipstream_openstack/OpenStackLibcloudPatch.py
Require slipstream/SlipStreamServer#640 (slipstream/SlipStreamServer@fe1513280d25b6a2f714d8d0defa5d31347c5610)
Connected to #90
=>  openstack improve v3 support

openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackSystemConfigurationParametersFactory.java, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackCommand.py, openstack/python/tar/slipstream_openstack/OpenStackLibcloudPatch.py
Connected to #92
:warning: **Require #91 to be merged first**
=> OpenStack: fix ip address retrieval

cloudstack/python/tar/slipstream_cloudstack/CloudStackAdvancedZoneClientCloud.py, cloudstack/python/tar/slipstream_cloudstack/CloudStackRunInstancesCommand.py
=> Fixed "CloudStackAdvancedZone ignore --networks".

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py
=> OpenStack: Fixed the "Build image".

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
=> Fix disk size to GB instead of MB

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackCommand.py
=> OpenStack: fixed a bug with the parameter domain

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
Connected to slipstream/SlipStreamConnectors/issues/109
=> OpenNebula connector add support for setting additional disk

openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackSystemConfigurationParametersFactory.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackUserParametersFactory.java, openstack/python/tar/bin/openstack-run-instances, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackLibcloudPatch.py
=> OpenStack: Added support for Floating IPs

opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaImageParametersFactory.java, opennebula/python/tar/slipstream_opennebula/OpenNebulaRunInstancesCommand.py
Connected to slipstream/SlipStreamUI#660
=> replace text cell by a text field area

opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaImageParametersFactory.java, opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py, opennebula/python/tar/slipstream_opennebula/OpenNebulaRunInstancesCommand.py
=> Issue #119 opennebula specific network selection

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
Connected to SixSq/NuvlaBox#205
=> Additional disk perf issue

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackLibcloudPatch.py, openstack/python/tar/test/TestOpenStackClientCloudLive.py, openstack/python/tar/test/pyunit.credentials.properties.ref
=> Issue #131 openstack additonal disk support

cloudstack/config/pom.xml, opennebula/config/pom.xml, openstack/config/pom.xml, stratuslab/config/pom.xml
Connected to slipstream/SlipStreamServer#916
=> dependency cleanup

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
=> add script in user data

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
Connected to slipstream/SlipStreamConnectors#140
=> Add support for root disk resize

opennebula/config/resources/com/sixsq/slipstream/connector/opennebula-desc.edn, opennebula/config/src/com/sixsq/slipstream/connector/opennebula_template.clj, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaImageParametersFactory.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaUserParametersFactory.java, opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py, opennebula/python/tar/slipstream_opennebula/OpenNebulaRunInstancesCommand.py
=> Issue #139 opennebula support contextualization type

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackCommand.py, openstack/python/tar/slipstream_openstack/OpenStackDescribeInstancesCommand.py, openstack/python/tar/slipstream_openstack/TestBaseLive.py, openstack/python/tar/test/TestOpenStackClientCloudLive.py, openstack/python/tar/test/pyunit.credentials.properties.ref
- check state of VM when waiting and throw on failed state
- refactored unit tests for code re-use in OTC connector
- minor refactors
Fixes #151
NB! It doesn't fix this one #138
Related to https://github.com/SixSq/SlipStreamConnectors/issues/71, https://github.com/SixSq/tasklist/issues/1120
Connected to #151
=> check state of VM when waiting and throw on failed state

openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py
=> openstack: Improved the way we retrieve IPs

cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackConnector.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabConnector.java
Connected to slipstream/SlipStreamServer#1047
=> Issue slipstream/slip stream server#1047 extend api manage cloudparameters at run creation

cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackConnector.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabConnector.java
Added service offers support for: 
- CloudStack
- OpenNebula
- OpenStack
- StratusLab
Connected to #157
Require slipstream/SlipStreamServer#1086
=> Added service offers support

cloudstack/python/tar/bin/cloudstack-service-offers, cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py, cloudstack/python/tar/slipstream_cloudstack/CloudStackServiceOffersCommand.py
Connected to #160
Require slipstream/SlipStreamClient#327
=> cloudstack: added scraper

cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py, openstack/python/tar/bin/openstack-service-offers, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackServiceOffersCommand.py
=> Implementation openstack scraper

opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaConnector.java, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabConnector.java
=> transform ram from MB to GB

cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackConnector.java, cloudstack/python/tar/slipstream_cloudstack/CloudStackServiceOffersCommand.py, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java, openstack/python/tar/slipstream_openstack/OpenStackServiceOffersCommand.py, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabConnector.java
Connected to slipstream/SlipStreamServer#1099
=> instancetype moved into resource attribute namespace

cloudstack/python/tar/slipstream_cloudstack/CloudStackServiceOffersCommand.py, opennebula/python/tar/slipstream_opennebula/OpenNebulaServiceOffersCommand.py
Connected to slipstream/SlipStream#240
Require slipstream/SlipStreamClient#332
=> Refactored scrapers

cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py, cloudstack/python/tar/test/TestCloudStackClientCloudLive.py, openstack/python/tar/slipstream_openstack/TestBaseLive.py, stratuslab/python/tar/test/TestStratusLabLiveBase.py
- access to max_iaas_worker was changed
NB! Merge after https://github.com/slipstream/SlipStreamClient/pull/340
Connected to #168
=> update after refactors in slipstream client

cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py, openstack/python/tar/slipstream_openstack/OpenStackClientCloud.py
Connected to slipstream/SlipStreamClient#355
=> fix go till microseconds

cloudstack/java/jar/pom.xml, opennebula/java/jar/pom.xml, openstack/java/jar/pom.xml, physicalhost/java/jar/pom.xml, stratuslab/java/jar/pom.xml
=> added dependency on SlipStreamCljResourcesTestServer test jar

opennebula/config/build.boot, opennebula/config/resources/com/sixsq/slipstream/connector/opennebula-cloud-cred-desc.edn, opennebula/config/src/com/sixsq/slipstream/ssclj/resources/credential_cloud_opennebula.clj, opennebula/config/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud_opennebula.clj, opennebula/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_opennebula.cljc, opennebula/config/test/com/sixsq/slipstream/ssclj/resources/credential_cloud_opennebula_lifecycle_test.clj, opennebula/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_opennebula_test.cljc, opennebula/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_opennebula_test.cljc, opennebula/java/jar/pom.xml, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaCloudCredDef.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaCredentials.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaSystemConfigurationParametersFactory.java, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaUserParametersFactory.java, opennebula/java/jar/src/test/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaCloudCredDefTest.java, opennebula/java/jar/src/test/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaCloudCredentialsTest.java
=> opennebula cred defs

openstack/config/build.boot, openstack/config/resources/com/sixsq/slipstream/connector/openstack-cloud-cred-desc.edn, openstack/config/src/com/sixsq/slipstream/ssclj/resources/credential_cloud_openstack.clj, openstack/config/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud_openstack.clj, openstack/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_openstack.cljc, openstack/config/test/com/sixsq/slipstream/ssclj/resources/credential_cloud_openstack_lifecycle_test.clj, openstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_openstack_test.cljc, openstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_openstack_test.cljc, openstack/java/jar/pom.xml, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackCloudCredDef.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackCredentials.java, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackUserParametersFactory.java, openstack/java/jar/src/test/java/com/sixsq/slipstream/connector/openstack/OpenStackCloudCredDefTest.java, openstack/java/jar/src/test/java/com/sixsq/slipstream/connector/openstack/OpenStackCloudCredentialsTest.java, openstack/java/jar/src/test/java/com/sixsq/slipstream/connector/openstack/OpenStackUserParametersFactoryTest.java
=> Update to credentials related code according to the changes in the base implementation

cloudstack/config/build.boot, cloudstack/config/resources/com/sixsq/slipstream/connector/cloudstack-cloud-cred-desc.edn, cloudstack/config/src/com/sixsq/slipstream/ssclj/resources/credential_cloud_cloudstack.clj, cloudstack/config/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud_cloudstack.clj, cloudstack/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_cloudstack.cljc, cloudstack/config/test/com/sixsq/slipstream/ssclj/resources/credential_cloud_cloudstack_lifecycle_test.clj, cloudstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_cloudstack_test.cljc, cloudstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_cloudstack_test.cljc, cloudstack/java/jar/pom.xml, cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackAdvancedZoneSystemConfigurationParametersFactory.java, cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackCloudCredDef.java, cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackCredentials.java, cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackUserParametersFactory.java, cloudstack/java/jar/src/test/java/com/sixsq/slipstream/connector/cloudstack/CloudStackCloudCredDefTest.java, cloudstack/java/jar/src/test/java/com/sixsq/slipstream/connector/cloudstack/CloudStackCloudCredentialsTest.java
=> Issue 184 cloudstack cred defs

cloudstack/config/build.boot, cloudstack/java/jar/src/main/java/com/sixsq/slipstream/connector/cloudstack/CloudStackCloudCredDef.java, opennebula/config/build.boot, opennebula/java/jar/src/main/java/com/sixsq/slipstream/connector/opennebula/OpenNebulaCloudCredDef.java, openstack/config/build.boot, openstack/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_openstack.cljc, openstack/config/src/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_openstack.cljc, openstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_cloud_openstack_test.cljc, openstack/config/test/com/sixsq/slipstream/ssclj/resources/spec/credential_template_cloud_openstack_test.cljc, openstack/java/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackCloudCredDef.java, physicalhost/java/jar/src/main/java/com/sixsq/slipstream/connector/physicalhost/PhysicalHostCredentials.java, stratuslab/config/build.boot, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabCloudCredDef.java, stratuslab/java/jar/src/main/java/com/sixsq/slipstream/connector/stratuslab/StratusLabIterCloudCredDef.java
=> update 'href' handling in per connector CloudCredDef

opennebula/python/tar/slipstream_opennebula/OpenNebulaClientCloud.py
=> fix raising string

openstack/python/tar/slipstream_openstack/OpenStackRunInstancesCommand.py
=> openstack: floating ip bug

cloudstack/python/tar/slipstream_cloudstack/CloudStackClientCloud.py
=> cloudstack: retrieve disk size when collecting vms.

cloudstack/python/tar/slipstream_cloudstack/LibcloudCloudstackPatch.py
Connected to slipstream/SlipStreamJobEngine#67
=> cloudstack: patched libcloud to be able to list instances even when ipaddress field is not present.
